app/profile/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField,StringField,BooleanField
from wtforms.validators import Required

class bio(FlaskForm):

    bio = StringField('Tell us about you',id='bio', validators=[Required()])
    submit = SubmitField('Update')

app/profile/__init__.py
from flask import Blueprint
profile = Blueprint('profile', __name__)
from . import views,forms

app/profile/views.py
from flask import render_template, redirect, url_for, request
from . import profile
from .. import db,photos
from ..models import User
from flask_login import login_required
from ..models import User
from .forms import bio


@profile.route('/user/profile/<uname>', methods= ['GET', 'POST'])
@login_required
def Profile(uname):
    user = User.query.filter_by(username = uname).first()

    return render_template('profile/profile.html' , user = user)

@profile.route('/user/update/profilepic/<uname>', methods = ['GET', 'POST'])
@login_required
def updateprofile(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic = path
        db.session.commit()

    return redirect(url_for('profile.Profile', uname = uname))

@profile.route('/user/update/bio/<uname>', methods= ['GET', 'POST'])
@login_required
def updatebio(uname):
    user = User.query.filter_by(username = uname).first()
    form =bio()
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.commit()

        return redirect(url_for('profile.Profile', uname = user.username))

    return render_template ('profile/bio.html', form =form, user = user)

app/templates/profile/bio.html
{%extends 'base.html'%}

{%block content%}

{%block styles%}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename ='profile.css')}}">
{%endblock%}
<div class="form">
{{wtf.quick_form(form)}}
</div>
<p><a class="back btn btn-success" href="{{url_for('profile.Profile', uname = user.username)}}">Go back to profiles</a></p>


{%endblock%}















 

app/templates/profile/profile.html
{%extends 'base.html'%}



{%block content%}
{%block styles%}
{{super()}}

<link rel="stylesheet" href="{{url_for('static', filename = 'profile.css')}}">
{%endblock%}
<div class="heading">
<hr>
<h1 class="pagetitle">Profile</h1>
<hr>
</div>
<div class="row">


    <div class="col-md-6">
        {%if current_user.profile_pic%}
        <img src="{{url_for('static', filename = user.profile_pic)}}" alt="">
        {%else%}

        <img src="{{url_for('static', filename = 'photos/pexels-annie-untalan-4015334.jpg')}}" alt="">
        {%endif%}


        <form action="{{url_for('profile.updateprofile', uname = user.username)}}" , method="post" ,
            enctype="multipart/form-data">
            <h5>Update profile</h5>
            <input type="file" name='photo' required>
            <input type="submit">
        </form>
    </div>
    <div class="col-md-5 bio card">
        <h2>{{user.username}}</h2>
        <h4>Bio</h4>
        {%if user.bio%}
        <p>{{user.bio}}</p>
        {%else%}
        <p>I am {{user.username}} and I don't have a Bio yet! </p>
        {%endif%}
        <p><a class="btn btn-success" href="{{url_for('profile.updatebio', uname = user.username)}}">Update Bio</a></p>
    </div>
</div>
{%endblock%}