app/blogs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField,TextAreaField,SubmitField
from wtforms.validators import Required

class Blog(FlaskForm):
    title = StringField('What is the Blog title', validators = [Required()])
    body =TextAreaField('Write Down Your Blog', validators=[Required()])
    submit = SubmitField('Submit')
class NewComment(FlaskForm):

    title = StringField('Enter the title of the comment')
    comment = TextAreaField('Write Down your comments bellow')
    submit = SubmitField('comment')

class Subscribe(FlaskForm):

    email = StringField('Enter your email address', validators=[Required()])
    submit = SubmitField('Subscribe')

class UpdateBlog(FlaskForm):

    
    body = StringField('Enter the update bellow')
    
    

app/blogs/__init__.py
from flask import Blueprint
blogs = Blueprint('blogs',__name__)
from . import views, forms 

app/blogs/views.py
from flask import render_template,redirect, url_for,flash
from .forms import Blog, NewComment, Subscribe
from . import blogs
from ..models import Blogs,Comment, Subscriber
from .. import db
from ..request import load_quote
from flask_login import login_required
from ..email import mail_message
from ..subscriber import get_subscribers



@blogs.route('/blogs/publish', methods = ['POST', 'GET'])
@login_required
def newblog():

    subscribers = get_subscribers()
    form = Blog()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data

        new_blog = Blogs(title = title, body = body)

        new_blog.save_blog()

        try:
            mail_message("New Blogs","email/new_blogs",subscribers)
        except:
            flash('Blog successfully posted')
        return redirect(url_for('.postedblogs'))
        
    return render_template('blogs/new.html', form = form)

@blogs.route('/blogs/posted')
@blogs.route('/')
def postedblogs():

    blogs = Blogs.query.all()
    comments = Comment.query.all()

    return render_template('blogs/posted.html', blogs = blogs, comments = comments)

@blogs.route('/blogs/<blog_id>/new/comments', methods = ['GET', 'POST'])
@login_required
def newcomment(blog_id):

    form = NewComment()
    if form.validate_on_submit():

        

        blog_id = blog_id
        title = form.title.data
        body = form.comment.data

        new_comment = Comment(blog_id = blog_id,title =title,body =body)

        new_comment.save_comment()

        

        return redirect(url_for('.postedblogs'))
    
    return render_template('comments/new.html',form = form)

@blogs.route('/subscibe', methods =['GET', 'POST'])
@login_required
def subscribe():
    form = Subscribe()
    if form.validate_on_submit():
        email = form.email.data

        new_subscriber = Subscriber(email = email)
        new_subscriber.save_subscriber()

        

        flash('You have successfully been added to our mailing list')
        return redirect(url_for('.postedblogs'))
    
    return render_template('subscribe.html', form =form)


@blogs.route('/quotes')
@login_required
def quote():
    quote = load_quote()

    return render_template('quotes.html', quote = quote)


@blogs.route('/delete/comment/<int:comment_id>')
@login_required
def deletecomment(comment_id):

    Comment.query.filter_by(id = comment_id).delete()
    db.session.commit()
    
    return redirect(url_for('.postedblogs'))


@blogs.route('/delete/blog/<int:blog_id>')
@login_required
def deleteblog(blog_id):

    Blogs.query.filter_by(id = blog_id).delete()
    db.session.commit()
    
    return redirect(url_for('.postedblogs'))

@blogs.route('/update/blog/<int:blog_id>')
@login_required
def updateblog(blog_id):

    Blog.query.filter_by(id = blog_id).first()
    

app/templates/blogs/new.html
{%extends 'base.html'%}
{%block content%}
{%block styles%}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename ='blogs.css')}}">
{%endblock%}
    <div class="form bg-success newblog">
        
        
        {{wtf.quick_form(form)}}
    </div>
{%endblock%}

app/templates/blogs/posted.html
{%extends 'base.html'%}

{%block content%}

{%block styles%}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename ='blogs.css')}}">
{%endblock%}

<p class="subscriber"><a href="{{url_for('blogs.subscribe')}}">Click here</a> to subscibe for notifications on new blogs
</p>
<div class="heading">
   <hr>
   <h1 class="pagetitle">Blogs</h1>
   <hr>
</div>

<div class="blogs card">

   {%for blog in blogs%}
   <div class="card"></div>
   <h1>{{blog.title}}</h1>
   <p>{{blog.body}}</p>
   <hr>
   <br>
   <br>
   <h4>Comments</h4>
   {%for comment in comments%}

   {%if comment.blog_id == blog.id%}
   <div class="card comment">

      <div class="comment">
         <p>{{comment.title}}</p>
         <p>{{comment.body}}</p>
      </div>

      <div class="delete ">
         <p><a class="btn-danger btn " href="{{url_for('blogs.deletecomment', comment_id = comment.id)}}">Delete
               Comment</a>
         </p>
      </div>

      <hr>
      <br>
      <hr>

   </div>
   <br>
   <hr>
   <br>
   {%endif%}
   {%endfor%}
   <p><a class='btn-success btn' href="/blogs/{{blog.id}}/new/comments">Add Comment</a></p>
   <p><a class="btn-danger btn" href="{{url_for('blogs.deleteblog', blog_id = blog.id)}}">Delete Blog</a></p>
</div>
{%endfor%}
</div>

{%endblock%}