app/Authentification/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SubmitField, SelectField, PasswordField
from wtforms.validators import ValidationError, Email, Required, EqualTo
from ..models import User

class SignUp(FlaskForm):
    username = StringField('Username:', validators=[Required()] )
    email = StringField('Email:', validators=[Required(), Email()])
    password = PasswordField('Password', validators=[Required(),EqualTo('confirm_password', 'Passwords must match')])
    confirm_password = PasswordField('Confirm Password', validators=[Required()])
    submit = SubmitField('Sign Up')

    # def validate_username(self,data_field):
    #     if User.query.filter_by(username = data_field.data).first():
    #         raise ValidationError('username already exists')

    # def validate_email(self, data_field):
    #     if User.query.filter_by(email = data_field.data):
    #         raise ValidationError('The email address has already been used')



class SignIn(FlaskForm):
    username = StringField('Username:', validators=[Required()] )
    email = StringField('Email:', validators=[Required(), Email()])
    password = PasswordField('Password', validators=[Required()])
    Remember = BooleanField('Remember me')
    submit = SubmitField('Sign In')

app/Authentification/__init__.py
from flask import Blueprint
auth = Blueprint('auth',__name__)
from .  import views, forms

app/Authentification/views.py
from flask import redirect, render_template, url_for,render_template, flash
from .forms import SignIn, SignUp
from ..models import User
from flask_login import login_user,logout_user
from . import auth
from .. import db
from flask_login import login_required


@auth.route('/profile/signup', methods = ['GET','POST'])
def signup():
    form = SignUp()

    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data

        new_user = User(username = username, email = email, password = password)

        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('auth.signin'))
    return render_template('authentification/Signup.html', form = form)
    
@auth.route('/profile/signin', methods = ['GET','POST'])
def signin():
    
    form = SignIn()
    
    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()

        

        if user is not None and user.password == form.password.data: 

            login_user(user,form.Remember.data)

            return redirect(url_for('blogs.postedblogs'))

        flash('Invalid username or password')

    
    return render_template('authentification/SignIn.html', form = form)

@auth.route('/profile/signout', methods = ['GET','POST'])
@login_required
def signout():

    logout_user()

    return redirect(url_for('auth.signin'))

app/templates/authentification/SignIn.html
{%extends 'base.html'%}

{%block content%}
{%block styles%}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename ='auth.css')}}">
{%endblock%}
<div class="form bg-success signing">
    <h6>Sign in</h6>
    {{wtf.quick_form(form)}}
</div>
<h4 class="account">Dont have an account? <a href="{{url_for('auth.signup')}}">Create an account.</a></h4>
{%endblock%}

app/templates/authentification/Signup.html
{%extends 'base.html'%}

{%block content%}
{%block styles%}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename ='auth.css')}}">
{%endblock%}

<div class="form bg-success signing">
    <h6>Sign up</h6>
    {{wtf.quick_form(form)}}
</div>

<h4 class="account">You already have an account? <a href="{{url_for('auth.signin')}}">Log In.</a></h4>
{%endblock%}